# This is a basic workflow to help you get started with Actions.

name: Aqua Enterprise image vulns assesment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Image_Scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull DVWA web application from vulnerables/web-dvwa
        run: |
          docker pull vulnerables/web-dvwa
    
      
      # Aqua Registry login
      - name: Login to Aqua Registry
        uses: docker/login-action@v1
        with:
          registry: registry.aquasec.com
          username: ${{ secrets.AQUADEV_USERNAME }}
          password: ${{ secrets.AQUADEV_PASS }}
      
      
      # Scan the test Image
      - name: Run the scanner 
        run: |
          docker run -e SCALOCK_LOG_LEVEL=DEBUG -e BUILD_JOB_NAME=FRUIT_BANK -e BUILD_NUMBER=${{ github.run_id }} -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 scan --host https://225fccbcb7.cloud.aquasec.com/ --local vulnerables/web-dvwa:latest --checkonly --no-verify --html --token dff831f47f675448e6adc97bba25a8befe9f6cc3 




