# This is a basic workflow to help you get started with Actions.

name: Trivi image vulns assesment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Image_Scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull DVWA web application from vulnerables/web-dvwa
        run: |
          docker pull vulnerables/web-dvwa
          docker save vulnerables/web-dvwa -o dvwa.tar
      - name: Run Trivy vulnerability scanner
        run: |
          docker pull aquasec/trivy:0.18.3
          docker run -v=$(pwd):/root/.cache aquasec/trivy:0.18.3 image  --exit-code 1 --severity CRITICAL --input  /root/.cache/dvwa.tar
      - if: failure()
        run: |
          echo "Image is bad"
      - if: success()
        run: |
          echo "Image is good!"



